name: Run fengchao.py with Base64 and password

on:
  schedule:
    - cron: '0 22-23 * * *'
    - cron: '30 22-23 * * *'
    - cron: '0 0-15 * * *'
    - cron: '30 0-15 * * *'
  workflow_dispatch:  

jobs:
  run-fengchao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch encrypted file from Cloudflare Worker
        run: |
          curl -o fengchao.py.base64 "https://bus-station.dannit.workers.dev/?pwd=${{ secrets.PASSWORD }}"

      - name: Decode the Base64 file
        run: |
          base64 -d fengchao.py.base64 > fengchao.py

      - name: Run fengchao.py
        run: |
          echo "Running fengchao.py"
          python fengchao.py
