name: Run fengchao.py from Base64 Secret

on:
  schedule:
    - cron: '0 22-23 * * *'
    - cron: '30 22-23 * * *'
    - cron: '0 0-15 * * *'
    - cron: '30 0-15 * * *'
  workflow_dispatch:

jobs:
  run-fengchao:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Write fengchao.py from Base64 Secret
        run: |
          echo "${{ secrets.FENGCHAO_BASE64 }}" | base64 -d > fengchao.py

      - name: Run fengchao.py
        run: |
          echo "Running fengchao.py"
          python fengchao.py
