name: Keep Alive

on:
  schedule:
    - cron: "0 0 */14 * *"   # 每 14 天的 0 点执行一次
  workflow_dispatch:

permissions:
  contents: write   # 允许 push

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update keepalive file
        run: |
          date > KEEPALIVE

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add KEEPALIVE
          git commit -m "chore: keep alive $(date)" || echo "No changes"
          git push
